-- Chinook schema (PostgreSQL) - converted from MySQL DDL
-- Tables: 11  |  Generated automatically

-- Database: Chinook_AutoIncrement
-- Export date: 2026-07-16 15:43:01
-- Total tables: 11

-- ============================================
-- Table: Album
-- ============================================
CREATE TABLE Album (
AlbumId INT GENERATED BY DEFAULT AS IDENTITY,
Title varchar(160) NOT NULL,
ArtistId int NOT NULL,
PRIMARY KEY (AlbumId)
);


-- ============================================
-- Table: Artist
-- ============================================
CREATE TABLE Artist (
ArtistId INT GENERATED BY DEFAULT AS IDENTITY,
Name varchar(120),
PRIMARY KEY (ArtistId)
);


-- ============================================
-- Table: Customer
-- ============================================
CREATE TABLE Customer (
CustomerId INT GENERATED BY DEFAULT AS IDENTITY,
FirstName varchar(40) NOT NULL,
LastName varchar(20) NOT NULL,
Company varchar(80),
Address varchar(70),
City varchar(40),
State varchar(40),
Country varchar(40),
PostalCode varchar(10),
Phone varchar(24),
Fax varchar(24),
Email varchar(60) NOT NULL,
SupportRepId int,
PRIMARY KEY (CustomerId)
);


-- ============================================
-- Table: Employee
-- ============================================
CREATE TABLE Employee (
EmployeeId INT GENERATED BY DEFAULT AS IDENTITY,
LastName varchar(20) NOT NULL,
FirstName varchar(20) NOT NULL,
Title varchar(30),
ReportsTo int,
BirthDate TIMESTAMP,
HireDate TIMESTAMP,
Address varchar(70),
City varchar(40),
State varchar(40),
Country varchar(40),
PostalCode varchar(10),
Phone varchar(24),
Fax varchar(24),
Email varchar(60),
PRIMARY KEY (EmployeeId)
);


-- ============================================
-- Table: Genre
-- ============================================
CREATE TABLE Genre (
GenreId INT GENERATED BY DEFAULT AS IDENTITY,
Name varchar(120),
PRIMARY KEY (GenreId)
);


-- ============================================
-- Table: Invoice
-- ============================================
CREATE TABLE Invoice (
InvoiceId INT GENERATED BY DEFAULT AS IDENTITY,
CustomerId int NOT NULL,
InvoiceDate TIMESTAMP NOT NULL,
BillingAddress varchar(70),
BillingCity varchar(40),
BillingState varchar(40),
BillingCountry varchar(40),
BillingPostalCode varchar(10),
Total decimal(10,2) NOT NULL,
PRIMARY KEY (InvoiceId)
);


-- ============================================
-- Table: InvoiceLine
-- ============================================
CREATE TABLE InvoiceLine (
InvoiceLineId INT GENERATED BY DEFAULT AS IDENTITY,
InvoiceId int NOT NULL,
TrackId int NOT NULL,
UnitPrice decimal(10,2) NOT NULL,
Quantity int NOT NULL,
PRIMARY KEY (InvoiceLineId)
);


-- ============================================
-- Table: MediaType
-- ============================================
CREATE TABLE MediaType (
MediaTypeId INT GENERATED BY DEFAULT AS IDENTITY,
Name varchar(120),
PRIMARY KEY (MediaTypeId)
);


-- ============================================
-- Table: Playlist
-- ============================================
CREATE TABLE Playlist (
PlaylistId INT GENERATED BY DEFAULT AS IDENTITY,
Name varchar(120),
PRIMARY KEY (PlaylistId)
);


-- ============================================
-- Table: PlaylistTrack
-- ============================================
CREATE TABLE PlaylistTrack (
PlaylistId int NOT NULL,
TrackId int NOT NULL,
PRIMARY KEY (PlaylistId,TrackId)
);


-- ============================================
-- Table: Track
-- ============================================
CREATE TABLE Track (
TrackId INT GENERATED BY DEFAULT AS IDENTITY,
Name varchar(200) NOT NULL,
AlbumId int,
MediaTypeId int NOT NULL,
GenreId int,
Composer varchar(220),
Milliseconds int NOT NULL,
Bytes int,
UnitPrice decimal(10,2) NOT NULL,
PRIMARY KEY (TrackId)
);

ALTER TABLE Album ADD CONSTRAINT FK_AlbumArtistId FOREIGN KEY (ArtistId) REFERENCES Artist (ArtistId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Customer ADD CONSTRAINT FK_CustomerSupportRepId FOREIGN KEY (SupportRepId) REFERENCES Employee (EmployeeId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Employee ADD CONSTRAINT FK_EmployeeReportsTo FOREIGN KEY (ReportsTo) REFERENCES Employee (EmployeeId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Invoice ADD CONSTRAINT FK_InvoiceCustomerId FOREIGN KEY (CustomerId) REFERENCES Customer (CustomerId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE InvoiceLine ADD CONSTRAINT FK_InvoiceLineInvoiceId FOREIGN KEY (InvoiceId) REFERENCES Invoice (InvoiceId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE InvoiceLine ADD CONSTRAINT FK_InvoiceLineTrackId FOREIGN KEY (TrackId) REFERENCES Track (TrackId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PlaylistTrack ADD CONSTRAINT FK_PlaylistTrackPlaylistId FOREIGN KEY (PlaylistId) REFERENCES Playlist (PlaylistId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE PlaylistTrack ADD CONSTRAINT FK_PlaylistTrackTrackId FOREIGN KEY (TrackId) REFERENCES Track (TrackId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Track ADD CONSTRAINT FK_TrackAlbumId FOREIGN KEY (AlbumId) REFERENCES Album (AlbumId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Track ADD CONSTRAINT FK_TrackGenreId FOREIGN KEY (GenreId) REFERENCES Genre (GenreId) ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE Track ADD CONSTRAINT FK_TrackMediaTypeId FOREIGN KEY (MediaTypeId) REFERENCES MediaType (MediaTypeId) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE INDEX IFK_AlbumArtistId ON Album (ArtistId);

CREATE INDEX IFK_CustomerSupportRepId ON Customer (SupportRepId);

CREATE INDEX IFK_EmployeeReportsTo ON Employee (ReportsTo);

CREATE INDEX IFK_InvoiceCustomerId ON Invoice (CustomerId);

CREATE INDEX IFK_InvoiceLineInvoiceId ON InvoiceLine (InvoiceId);

CREATE INDEX IFK_InvoiceLineTrackId ON InvoiceLine (TrackId);

CREATE INDEX IFK_PlaylistTrackPlaylistId ON PlaylistTrack (PlaylistId);

CREATE INDEX IFK_PlaylistTrackTrackId ON PlaylistTrack (TrackId);

CREATE INDEX IFK_TrackAlbumId ON Track (AlbumId);

CREATE INDEX IFK_TrackGenreId ON Track (GenreId);

CREATE INDEX IFK_TrackMediaTypeId ON Track (MediaTypeId);
